Pseudostyling
SMITHsharon/pseudoclasses pull request #1
Opened 2017-01-24 05:49 UTC by SMITHsharon

2017-01-24 15:30 UTC, justinal64 commented on index.html
> +    <article class="n-child">
According to the readme step 4 "In the article element with the class n-child, add a 1 pixel border around every even numbered section element." Currently you have a border around section element 2 and 4, but you don;t have one around element 0 which is an even number.

2017-01-24 15:32 UTC, justinal64 commented on pseudo.css
> +	margin: 25px 25px 25px 25px;
Zoey might not have taught you yet, but you can replace margin: 25px 25px 25px 25px; With margin: 25px; This will assign 25px margin to all 4 sides.

2017-01-24 15:33 UTC, justinal64 requested changes
Let me know if you have any questions about the comments I left.

2017-01-25 07:00 UTC, SMITHsharon commented on index.html
> +    <article class="n-child">
I think mine is already correct? So we shall talk about it on Saturday?

2017-01-25 07:02 UTC, SMITHsharon commented on pseudo.css
> +	margin: 25px 25px 25px 25px;
I revised this. I knew this already. I had written it this way at first, but the screen wrote in a weird way, so I wrote it out explicitly. Never went back and changed it back after reworking other things : /

2017-01-25 07:07 UTC, SMITHsharon commented
@justinal64 :: I revised the margin; left the pixel border unchanged, to talk about later on Saturday.

2017-01-25 16:03 UTC, justinal64 commented
@SMITHsharon if you think it's correct go ahead and merge it in. Sometimes the instructions aren't as clear as they should be, so there is room for us to interpate things differently. 👍

2017-01-28 15:25 UTC, merged